services:
  vector_db:
    profiles: ["server"]
    image: pgvector/pgvector:0.8.0-pg17-trixie
    container_name: vector_db
    environment:
      - POSTGRES_PASSWORD=password123123!
      - POSTGRES_USER=aip_user
      - POSTGRES_HOST=AiP_pg
      - POSTGRES_DB=aip_db
    ports:
      - 5432:5432
    volumes:
      - ./sql:/sql
      - ./data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

#  ollama:
#    profiles: ["experimental"]
#    image: ollama/ollama:latest
#    container_name: ollama
#    ports:
#      - "11434:11434"
#    volumes:
#      - ./data/ollama:/root/.ollama
#      - ./start_ollama.sh:/start_ollama.sh
#    entrypoint: ["/bin/bash", "/start_ollama.sh"]
#    deploy:
#      resources:
#        limits:
#          cpus: "7"
#
#  python-base:
#    profiles: ["base"]
#    build:
#      context: ./
#      dockerfile: ./dockerfiles/base.Dockerfile
#    image: nrc/base:latest
#    environment:
#      - TZ=America/Moncton
#
#  mcp_server:
#    profiles: ["experimental"]
#    build:
#      context: ./
#      dockerfile: ./dockerfiles/mcp_server.Dockerfile
#    image: nrc/mcp_server:latest
#    container_name: mcp_server
#    environment:
#      - TZ=America/Moncton
#    ports:
#      - 8000:8000
#    volumes:
#      - ../src:/src
#
#  jupyterlab:
#    profiles: ["experimental"]
#    build:
#      context: ./
#      dockerfile: ./dockerfiles/jupyter.Dockerfile
#    image: nrc/jupyter:latest
#    container_name: jupyterlab
#    environment:
#      - TZ=America/Moncton
#    ports:
#      - 8888:8888
#    volumes:
#      - ../src/jupyter:/src/jupyter
